// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealTimePolls.Data;

#nullable disable

namespace RealTimePolls.Migrations
{
    [DbContext(typeof(RealTimePollsDbContext))]
    [Migration("20240517062044_Seeded Genres")]
    partial class SeededGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("realTimePolls.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Food & Cooking"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Art & Design"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Anime"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Environment"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Business & Finance"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Movies & TV"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 19,
                            Name = "History"
                        },
                        new
                        {
                            Id = 20,
                            Name = "DIY & Crafts"
                        });
                });

            modelBuilder.Entity("realTimePolls.Models.Poll", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("FirstOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("firstoption");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genreid");

                    b.Property<string>("SecondOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("secondoption");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("realTimePolls.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("googleid");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profilepicture");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("realTimePolls.Models.UserPoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("int")
                        .HasColumnName("pollid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.Property<bool?>("Vote")
                        .HasColumnType("bit")
                        .HasColumnName("vote");

                    b.HasKey("Id");

                    b.ToTable("UserPoll");
                });

            modelBuilder.Entity("realTimePolls.Models.Poll", b =>
                {
                    b.HasOne("realTimePolls.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
