// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealTimePolls.Data;

#nullable disable

namespace RealTimePolls.Migrations
{
    [DbContext(typeof(RealTimePollsDbContext))]
    [Migration("20240520022759_Added User fk relationship")]
    partial class AddedUserfkrelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealTimePolls.Models.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Food & Cooking"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Art & Design"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Anime"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Environment"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Business & Finance"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Movies & TV"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 19,
                            Name = "History"
                        },
                        new
                        {
                            Id = 20,
                            Name = "DIY & Crafts"
                        });
                });

            modelBuilder.Entity("RealTimePolls.Models.Domain.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("SecondOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("UserId");

                    b.ToTable("Polls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstOption = "Chicken",
                            GenreId = 2,
                            SecondOption = "Egg",
                            Title = "Which came first?",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstOption = "First choice",
                            GenreId = 5,
                            SecondOption = "Second choice",
                            Title = "What is your option?",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RealTimePolls.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "shawncarter123456@gmail.com",
                            GoogleId = "9999999",
                            Name = "Windows 10",
                            ProfilePicture = "https://image.png"
                        });
                });

            modelBuilder.Entity("RealTimePolls.Models.Domain.UserPoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Vote")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserPoll");
                });

            modelBuilder.Entity("RealTimePolls.Models.Domain.Poll", b =>
                {
                    b.HasOne("RealTimePolls.Models.Domain.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealTimePolls.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
